services:
  userdb:
    container_name: user-db
    image: postgres:14-alpine
    restart: always
    ports:
      - "4001:5432"
    volumes:
      - "./.docker-volumes/userdb:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user
    networks:
      - shopping-platform

networks:
  shopping-platform:
    driver: bridge